export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const INCREMENT_ASYNC = 'INCREMENT_SYNC';

export const API_REQUEST = 'API_REQUEST';
export const API_REQUEST_SUCCEEDED = 'API_REQUEST_SUCCEEDED';
export const API_REQUEST_FAILED = 'API_REQUEST_FAILED';

export const RETRIEVE_TOKEN = 'RETRIEVE_TOKEN';
export const RETRIEVE_TOKEN_ASYNC = 'RETRIEVE_TOKEN_ASYNC';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
